@startuml ActivityDiagram

start
:PythonTransformers erkennt das Bild;
:PythonTransformers -> TouchDesignerUI: Daten senden;

if (Touchdesigner bestätigt?) then (ja)
    :TouchDesignerUI bestätigt;
    :TouchDesignerUI -> PythonBilderstellung: Aufruf;
    :PythonBilderstellung -> ChatGPTAPI: Prompt erstellen;
    :PythonBilderstellung -> StableDiffusionAPI: Bild mit Prompt erstellen;
    :PythonBilderstellung -> TouchDesignerUI: Bild übermitteln;
    :TouchDesignerUI -> Processing: Beamersteuerung anpassen;
   
else (nein)
    

Endif 
    stop 




@enduml
