@startuml Components

package "Bilderkennung" {
    [PythonTransformers]
}

package "UI Komponenten /Frontend" {
    [TouchDesignerUI]
}

package "Bilderstellung" {
    [ChatGPTAPI]
    [StableDiffusionAPI]
    [Processing]
}

package "Backend" {
   
    [PythonBilderstellung]
}

PythonTransformers --> TouchDesignerUI : "Bilderkennung"
TouchDesignerUI --> PythonBilderstellung 
PythonBilderstellung --> ChatGPTAPI : "Bilderstellung"
ChatGPTAPI --> StableDiffusionAPI : "Bilderstellung"
PythonBilderstellung --..--> TouchDesignerUI : "Bildübermittlung"
TouchDesignerUI --> Processing : "Beamersteuerung"

@enduml
