# Use the ollama/ollama image as the base image
FROM ollama/ollama


# Setzen Sie das Arbeitsverzeichnis
WORKDIR /app

# Kopieren Sie die Modelfile.txt in das Arbeitsverzeichnis
COPY Modelfile /app/


ENV SERVER_SECRET="?#+oyNJnBw8WkbZV-lF7=7Z$,SlcC"


# Expose port 5000 to the outside world
EXPOSE 5000

